/** @format */

export default [
  { code: "aa", name: "Afar", local: [], translate: false },
  { code: "ab", name: "Abkhazian", local: [], translate: false },
  { code: "af", name: "Afrikaans", local: [], translate: true },
  { code: "ak", name: "Akan", local: [], translate: false },
  { code: "als", name: "Alemannic", local: [], translate: false },
  { code: "am", name: "Amharic", local: [], translate: true },
  { code: "an", name: "Aragonese", local: [], translate: false },
  { code: "ang", name: "Angal", local: [], translate: false },
  { code: "ar", name: "Arabic", local: [], translate: true },
  { code: "arc", name: "Aramaic", local: [], translate: false },
  { code: "as", name: "Assamese", local: [], translate: false },
  { code: "ast", name: "Asturian", local: [], translate: false },
  { code: "av", name: "Avar", local: [], translate: false },
  { code: "awa", name: "Awadhi", local: [], translate: false },
  { code: "ay", name: "Aymara", local: [], translate: false },
  { code: "az", name: "Azerbaijani", local: [], translate: true },
  { code: "ba", name: "Bashkir", local: [], translate: false },
  { code: "bar", name: "Bavarian", local: [], translate: false },
  { code: "bat-smg", name: "Samogitian", local: [], translate: false },
  { code: "bcl", name: "Bikol", local: [], translate: false },
  { code: "be", name: "Belarusian", local: [], translate: true },
  {
    code: "be-x-old",
    name: "Belarusian (Taraškievica)",
    local: [],
    translate: false,
  },
  { code: "bg", name: "Bulgarian", local: [], translate: true },
  { code: "bh", name: "Bihari", local: [], translate: false },
  { code: "bi", name: "Bislama", local: [], translate: false },
  { code: "bm", name: "Bambara", local: [], translate: false },
  { code: "bn", name: "Bengali", local: [], translate: true },
  { code: "bo", name: "Tibetan", local: [], translate: false },
  { code: "bpy", name: "Bishnupriya Manipuri", local: [], translate: false },
  { code: "br", name: "Breton", local: [], translate: false },
  { code: "brx", name: "Boro", local: [], translate: false },
  { code: "bs", name: "Bosnian", local: [], translate: true },
  { code: "bug", name: "Buginese", local: [], translate: false },
  { code: "bxr", name: "Buriat (Russia)", local: [], translate: false },
  { code: "ca", name: "Catalan", local: [], translate: true },
  { code: "cdo", name: "Min Dong Chinese", local: [], translate: false },
  { code: "ce", name: "Chechen", local: [], translate: false },
  { code: "ceb", name: "Cebuano", local: [], translate: true },
  { code: "ch", name: "Chamorro", local: [], translate: false },
  { code: "cho", name: "Choctaw", local: [], translate: false },
  { code: "chr", name: "Cherokee", local: [], translate: false },
  { code: "chy", name: "Cheyenne", local: [], translate: false },
  { code: "ckb", name: "Kurdish (Sorani)", local: [], translate: false },
  { code: "co", name: "Corsican", local: [], translate: true },
  { code: "cr", name: "Cree", local: [], translate: false },
  { code: "cs", name: "Czech", local: [], translate: true },
  { code: "csb", name: "Kashubian", local: [], translate: false },
  { code: "cu", name: "Old Church Slavonic", local: [], translate: false },
  { code: "cv", name: "Chuvash", local: [], translate: false },
  { code: "cy", name: "Welsh", local: [], translate: true },
  { code: "da", name: "Danish", local: [], translate: true },
  { code: "de", name: "German", local: [], translate: true },
  { code: "diq", name: "Dimli", local: [], translate: false },
  { code: "dsb", name: "Lower Sorbian", local: [], translate: false },
  { code: "dv", name: "Divehi", local: [], translate: false },
  { code: "dz", name: "Dzongkha", local: [], translate: false },
  { code: "ee", name: "Ewe", local: [], translate: false },
  { code: "el", name: "Greek", local: [], translate: true },
  { code: "en", name: "English", local: [], translate: true },
  { code: "en-gb", name: "English", local: [], translate: false },
  { code: "en-us", name: "English", local: [], translate: false },
  { code: "eo", name: "Esperanto", local: [], translate: true },
  { code: "es", name: "Spanish", local: [], translate: true },
  { code: "et", name: "Estonian", local: [], translate: true },
  { code: "eu", name: "Basque", local: [], translate: true },
  { code: "ext", name: "Extremaduran", local: [], translate: false },
  { code: "fa", name: "Persian", local: [], translate: true },
  { code: "ff", name: "Peul", local: [], translate: false },
  { code: "fi", name: "Finnish", local: [], translate: true },
  { code: "fiu-vro", name: "Võro", local: [], translate: false },
  { code: "fj", name: "Fijian", local: [], translate: false },
  { code: "fo", name: "Faroese", local: [], translate: false },
  { code: "fr", name: "French", local: [], translate: true },
  { code: "frp", name: "Arpitan", local: [], translate: false },
  { code: "fur", name: "Friulian", local: [], translate: false },
  { code: "fy", name: "West Frisian", local: [], translate: true },
  { code: "ga", name: "Irish", local: [], translate: true },
  { code: "gan", name: "Gan Chinese", local: [], translate: false },
  { code: "gbm", name: "Garhwali", local: [], translate: false },
  { code: "gd", name: "Scottish Gaelic", local: [], translate: true },
  { code: "gil", name: "Gilbertese", local: [], translate: false },
  { code: "gl", name: "Galician", local: [], translate: true },
  { code: "gn", name: "Guarani", local: [], translate: false },
  { code: "got", name: "Gothic", local: [], translate: false },
  { code: "gu", name: "Gujarati", local: [], translate: true },
  { code: "gv", name: "Manx", local: [], translate: false },
  { code: "ha", name: "Hausa", local: [], translate: true },
  { code: "hak", name: "Hakka Chinese", local: [], translate: false },
  { code: "haw", name: "Hawaiian", local: [], translate: true },
  { code: "he", name: "Hebrew", local: [], translate: true },
  { code: "hi", name: "Hindi", local: [], translate: true },
  { code: "ho", name: "Hiri Motu", local: [], translate: false },
  { code: "hr", name: "Croatian", local: [], translate: true },
  { code: "ht", name: "Haitian", local: [], translate: true },
  { code: "hu", name: "Hungarian", local: [], translate: true },
  { code: "hy", name: "Armenian", local: [], translate: true },
  { code: "hz", name: "Herero", local: [], translate: false },
  { code: "ia", name: "Interlingua", local: [], translate: false },
  { code: "id", name: "Indonesian", local: [], translate: true },
  { code: "ie", name: "Interlingue", local: [], translate: false },
  { code: "ig", name: "Igbo", local: [], translate: true },
  { code: "ii", name: "Sichuan Yi", local: [], translate: false },
  { code: "ik", name: "Inupiak", local: [], translate: false },
  { code: "ilo", name: "Ilokano", local: [], translate: false },
  { code: "inh", name: "Ingush", local: [], translate: false },
  { code: "io", name: "Ido", local: [], translate: false },
  { code: "is", name: "Icelandic", local: [], translate: true },
  { code: "it", name: "Italian", local: [], translate: true },
  { code: "iu", name: "Inuktitut", local: [], translate: false },
  { code: "ja", name: "Japanese", local: [], translate: true },
  { code: "jbo", name: "Lojban", local: [], translate: false },
  { code: "jv", name: "Javanese", local: [], translate: false },
  { code: "ka", name: "Georgian", local: [], translate: true },
  { code: "kg", name: "Kongo", local: [], translate: false },
  { code: "ki", name: "Kikuyu", local: [], translate: false },
  { code: "kj", name: "Kuanyama", local: [], translate: false },
  { code: "kk", name: "Kazakh", local: [], translate: true },
  { code: "kl", name: "Greenlandic", local: [], translate: false },
  { code: "km", name: "Cambodian", local: [], translate: true },
  { code: "kn", name: "Kannada", local: [], translate: true },
  { code: "khw", name: "Khowar", local: [], translate: false },
  { code: "ko", name: "Korean", local: [], translate: true },
  { code: "kr", name: "Kanuri", local: [], translate: false },
  { code: "ks", name: "Kashmiri", local: [], translate: false },
  { code: "ksh", name: "Ripuarian", local: [], translate: false },
  { code: "ku", name: "Kurdish (Kurmanji)", local: [], translate: true },
  { code: "kv", name: "Komi", local: [], translate: false },
  { code: "kw", name: "Cornish", local: [], translate: false },
  { code: "ky", name: "Kirghiz", local: [], translate: true },
  { code: "la", name: "Latin", local: [], translate: true },
  { code: "lad", name: "Ladino", local: [], translate: false },
  { code: "lan", name: "Lango", local: [], translate: false },
  { code: "lb", name: "Luxembourgish", local: [], translate: true },
  { code: "lg", name: "Ganda", local: [], translate: false },
  { code: "li", name: "Limburgian", local: [], translate: false },
  { code: "lij", name: "Ligurian", local: [], translate: false },
  { code: "lmo", name: "Lombard", local: [], translate: false },
  { code: "ln", name: "Lingala", local: [], translate: false },
  { code: "lo", name: "Laotian", local: [], translate: true },
  { code: "lzz", name: "Laz", local: [], translate: false },
  { code: "lt", name: "Lithuanian", local: [], translate: true },
  { code: "lv", name: "Latvian", local: [], translate: true },
  { code: "map-bms", name: "Banyumasan", local: [], translate: false },
  { code: "mg", name: "Malagasy", local: [], translate: true },
  { code: "man", name: "Mandarin", local: [], translate: false },
  { code: "mh", name: "Marshallese", local: [], translate: false },
  { code: "mi", name: "Māori", local: [], translate: true },
  { code: "min", name: "Minangkabau", local: [], translate: false },
  { code: "mk", name: "Macedonian", local: [], translate: true },
  { code: "ml", name: "Malayalam", local: [], translate: true },
  { code: "mn", name: "Mongolian", local: [], translate: true },
  { code: "mo", name: "Moldovan", local: [], translate: false },
  { code: "mr", name: "Marathi", local: [], translate: true },
  { code: "mrh", name: "Mara", local: [], translate: false },
  { code: "ms", name: "Malay", local: [], translate: true },
  { code: "mt", name: "Maltese", local: [], translate: true },
  { code: "mus", name: "Creek", local: [], translate: false },
  { code: "mwl", name: "Mirandese", local: [], translate: false },
  { code: "my", name: "Burmese", local: [], translate: true },
  { code: "na", name: "Nauruan", local: [], translate: false },
  { code: "nah", name: "Nahuatl", local: [], translate: false },
  { code: "nap", name: "Neapolitan", local: [], translate: false },
  { code: "nd", name: "North Nbedele", local: [], translate: false },
  { code: "nds", name: "German Low Saxon", local: [], translate: false },
  { code: "nds-nl", name: "Dutch Low Saxon", local: [], translate: false },
  { code: "ne", name: "Nepali", local: [], translate: true },
  { code: "new", name: "Newar", local: [], translate: false },
  { code: "ng", name: "Ndonga", local: [], translate: false },
  { code: "nl", name: "Dutch", local: [], translate: true },
  { code: "nn", name: "Norwegian Nynorsk", local: [], translate: false },
  { code: "no", name: "Norwegian", local: [], translate: true },
  { code: "nr", name: "South Ndebele", local: [], translate: false },
  { code: "nso", name: "Northern Sotho", local: [], translate: false },
  { code: "nrm", name: "Norman", local: [], translate: false },
  { code: "nv", name: "Navajo", local: [], translate: false },
  { code: "ny", name: "Chichewa", local: [], translate: true },
  { code: "oc", name: "Occitan", local: [], translate: false },
  { code: "oj", name: "Ojibwa", local: [], translate: false },
  { code: "om", name: "Oromo", local: [], translate: false },
  { code: "or", name: "Oriya", local: [], translate: false },
  { code: "os", name: "Ossetian", local: [], translate: false },
  { code: "owo", name: "OwO", local: [], translate: false },
  { code: "pa", name: "Panjabi", local: [], translate: true },
  { code: "pag", name: "Pangasinan", local: [], translate: false },
  { code: "pam", name: "Kapampangan", local: [], translate: false },
  { code: "pap", name: "Papiamentu", local: [], translate: false },
  { code: "pdc", name: "Pennsylvania German", local: [], translate: false },
  { code: "pi", name: "Pali", local: [], translate: false },
  { code: "pih", name: "Norfolk", local: [], translate: false },
  { code: "pl", name: "Polish", local: [], translate: true },
  { code: "pms", name: "Piedmontese", local: [], translate: false },
  { code: "ps", name: "Pashto", local: [], translate: true },
  { code: "pt", name: "Portuguese", local: [], translate: true },
  { code: "qu", name: "Quechua", local: [], translate: false },
  { code: "rm", name: "Raeto Romance", local: [], translate: false },
  { code: "rmy", name: "Romani", local: [], translate: false },
  { code: "rn", name: "Kirundi", local: [], translate: false },
  { code: "ro", name: "Romanian", local: [], translate: true },
  { code: "roa-rup", name: "Aromanian", local: [], translate: false },
  { code: "ru", name: "Russian", local: [], translate: true },
  { code: "rw", name: "Rwandi", local: [], translate: false },
  { code: "sa", name: "Sanskrit", local: [], translate: false },
  { code: "sc", name: "Sardinian", local: [], translate: false },
  { code: "scn", name: "Sicilian", local: [], translate: false },
  { code: "sco", name: "Scots", local: [], translate: false },
  { code: "sd", name: "Sindhi", local: [], translate: true },
  { code: "se", name: "Northern Sami", local: [], translate: false },
  { code: "sg", name: "Sango", local: [], translate: false },
  { code: "sh", name: "Serbo-Croatian", local: [], translate: false },
  { code: "si", name: "Sinhalese", local: [], translate: true },
  { code: "simple", name: "Simple English", local: [], translate: false },
  { code: "sk", name: "Slovak", local: [], translate: true },
  { code: "sl", name: "Slovenian", local: [], translate: true },
  { code: "sm", name: "Samoan", local: [], translate: true },
  { code: "sn", name: "Shona", local: [], translate: true },
  { code: "so", name: "Somalia", local: [], translate: true },
  { code: "sq", name: "Albanian", local: [], translate: true },
  { code: "sr", name: "Serbian", local: [], translate: true },
  { code: "ss", name: "Swati", local: [], translate: false },
  { code: "st", name: "Southern Sotho", local: [], translate: true },
  { code: "su", name: "Sundanese", local: [], translate: true },
  { code: "sv", name: "Swedish", local: [], translate: true },
  { code: "sw", name: "Swahili", local: [], translate: true },
  { code: "ta", name: "Tamil", local: [], translate: true },
  { code: "te", name: "Telugu", local: [], translate: true },
  { code: "tet", name: "Tetum", local: [], translate: false },
  { code: "tg", name: "Tajik", local: [], translate: true },
  { code: "th", name: "Thai", local: [], translate: true },
  { code: "ti", name: "Tigrinya", local: [], translate: false },
  { code: "tk", name: "Turkmen", local: [], translate: false },
  { code: "tl", name: "Tagalog", local: [], translate: true },
  { code: "tlh", name: "Klingon", local: [], translate: false },
  { code: "tn", name: "Tswana", local: [], translate: false },
  { code: "to", name: "Tonga", local: [], translate: false },
  { code: "tpi", name: "Tok Pisin", local: [], translate: false },
  { code: "tr", name: "Turkish", local: [], translate: true },
  { code: "ts", name: "Tsonga", local: [], translate: false },
  { code: "tt", name: "Tatar", local: [], translate: false },
  { code: "tum", name: "Tumbuka", local: [], translate: false },
  { code: "tw", name: "Twi", local: [], translate: false },
  { code: "ty", name: "Tahitian", local: [], translate: false },
  { code: "udm", name: "Udmurt", local: [], translate: false },
  { code: "ug", name: "Uyghur", local: [], translate: false },
  { code: "uk", name: "Ukrainian", local: [], translate: true },
  { code: "ur", name: "Urdu", local: [], translate: true },
  { code: "uz", name: "Uzbek", local: [], translate: true },
  { code: "uz_AF", name: "Uzbeki Afghanistan", local: [], translate: false },
  { code: "uwu", name: "UwU", local: [], translate: false },
  { code: "ve", name: "Venda", local: [], translate: false },
  { code: "vi", name: "Vietnamese", local: [], translate: true },
  { code: "vec", name: "Venetian", local: [], translate: false },
  { code: "vls", name: "West Flemish", local: [], translate: false },
  { code: "vo", name: "Volapük", local: [], translate: false },
  { code: "wa", name: "Walloon", local: [], translate: false },
  { code: "war", name: "Waray", local: [], translate: false },
  { code: "wo", name: "Wolof", local: [], translate: false },
  { code: "xal", name: "Kalmyk", local: [], translate: false },
  { code: "xh", name: "Xhosa", local: [], translate: true },
  { code: "xmf", name: "Megrelian", local: [], translate: false },
  { code: "yi", name: "Yiddish", local: [], translate: true },
  { code: "yo", name: "Yoruba", local: [], translate: true },
  { code: "za", name: "Zhuang", local: [], translate: false },
  { code: "zh-cn", name: "Chinese", local: [], translate: true },
  { code: "zh-tw", name: "Traditional Chinese", local: [], translate: true },
  { code: "zh-min-nan", name: "Minnan", local: [], translate: false },
  { code: "zh-yue", name: "Cantonese", local: [], translate: false },
  { code: "zu", name: "Zulu", local: [], translate: true },
];
